export type EventTemplate = {
  name: string;
  description: string;
  intensity: "low" | "medium" | "high";
  milestones: {
    title: string;
    description?: string;
  }[];
};

export const eventTemplates: EventTemplate[] = [
  {
    name: "Annual Day",
    description: "Annual cultural celebration with student performances and invited guests.",
    intensity: "high",
    milestones: [
      { title: "Finalize event date" },
      { title: "Prepare cultural programme list" },
      { title: "Assign event coordinators" },
      { title: "Prepare student participation list" },
      { title: "Prepare costume requirement" },
      { title: "Prepare invitation draft" },
      { title: "Confirm chief guest" },
      { title: "Stage and sound arrangement" },
      { title: "Rehearsal schedule" },
      { title: "Parent circular" },
      { title: "Certificate/memento preparation" },
      { title: "Final rehearsal" },
      { title: "Post-event report" },
    ],
  },
  {
    name: "Sports Day",
    description: "Sports event with competitions, duties, certificates, and ground readiness.",
    intensity: "high",
    milestones: [
      { title: "Finalize sports day date" },
      { title: "Prepare event list" },
      { title: "Assign house-wise responsibilities" },
      { title: "Prepare student participant list" },
      { title: "Ground marking and equipment check" },
      { title: "Medical and hydration arrangement" },
      { title: "Volunteer duty chart" },
      { title: "Prize and certificate preparation" },
      { title: "Chief guest confirmation" },
      { title: "Final ground inspection" },
      { title: "Post-event report" },
    ],
  },
  {
    name: "Parent Teacher Meeting",
    description: "Class-wise parent interaction and academic progress review.",
    intensity: "medium",
    milestones: [
      { title: "Finalize PTM date" },
      { title: "Prepare parent circular" },
      { title: "Prepare class-wise progress sheets" },
      { title: "Confirm teacher availability" },
      { title: "Arrange classrooms" },
      { title: "Prepare feedback forms" },
      { title: "Record parent attendance" },
      { title: "Submit post-PTM issue summary" },
    ],
  },
  {
    name: "Unit Test",
    description: "Unit assessment planning, papers, invigilation, and result readiness.",
    intensity: "medium",
    milestones: [
      { title: "Finalize test timetable" },
      { title: "Collect question papers" },
      { title: "Print answer sheets" },
      { title: "Prepare seating plan" },
      { title: "Assign invigilation duties" },
      { title: "Confirm evaluation timeline" },
      { title: "Prepare marks entry sheet" },
      { title: "Publish result summary" },
    ],
  },
  {
    name: "Half-Yearly Examination",
    description: "Formal examination cycle with timetable, papers, invigilation, and reporting.",
    intensity: "high",
    milestones: [
      { title: "Finalize examination timetable" },
      { title: "Prepare syllabus circular" },
      { title: "Collect question papers" },
      { title: "Review paper format" },
      { title: "Print and seal question papers" },
      { title: "Prepare seating arrangement" },
      { title: "Assign invigilation duties" },
      { title: "Prepare evaluation schedule" },
      { title: "Marks entry verification" },
      { title: "Report card preparation" },
      { title: "Result review meeting" },
    ],
  },
  {
    name: "Science Exhibition",
    description: "Student science project showcase with judging and display readiness.",
    intensity: "high",
    milestones: [
      { title: "Finalize exhibition date" },
      { title: "Collect project nominations" },
      { title: "Shortlist projects" },
      { title: "Assign display spaces" },
      { title: "Prepare judging criteria" },
      { title: "Confirm judges" },
      { title: "Arrange electrical and safety support" },
      { title: "Prepare certificates" },
      { title: "Final project review" },
      { title: "Post-event report" },
    ],
  },
  {
    name: "School Inspection",
    description: "Institution readiness review for records, compliance, and leadership briefing.",
    intensity: "high",
    milestones: [
      { title: "Academic records check" },
      { title: "Teacher lesson plan file" },
      { title: "Attendance records" },
      { title: "Lab records" },
      { title: "Library records" },
      { title: "Safety certificates" },
      { title: "Activity reports" },
      { title: "Staff files" },
      { title: "Infrastructure records" },
      { title: "Final inspection brief" },
    ],
  },
  {
    name: "Field Trip",
    description: "Student visit planning with consent, transport, safety, and reporting.",
    intensity: "medium",
    milestones: [
      { title: "Finalize destination" },
      { title: "Collect parent consent forms" },
      { title: "Prepare student list" },
      { title: "Arrange transport" },
      { title: "Assign teacher escorts" },
      { title: "Prepare safety instructions" },
      { title: "Confirm food and water plan" },
      { title: "Emergency contact sheet" },
      { title: "Post-trip report" },
    ],
  },
  {
    name: "Morning Assembly Duty",
    description: "Routine assembly planning with anchors, prayer, announcements, and duty ownership.",
    intensity: "low",
    milestones: [
      { title: "Prepare assembly duty rota" },
      { title: "Assign student anchors" },
      { title: "Prepare thought for the day" },
      { title: "Confirm prayer and pledge team" },
      { title: "Collect announcements" },
      { title: "Check sound system" },
      { title: "Record assembly completion" },
    ],
  },
];
